name: sample_flutter_202210
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_hooks: ^0.18.5
  hooks_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.2

  dio: ^4.0.6
  retrofit: ^3.3.1

  go_router: ^6.0.0

  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:

  flutter_lints: ^2.0.0

  riverpod_generator: ^1.0.2
  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'
  freezed: ^2.1.1

flutter:
  uses-material-design: true
