name: sample_flutter_202210
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  hooks_riverpod: ^2.0.2
  go_router: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
